export class TriggerConstants {
  static CONDITION_TYPE_TIME = 0
  static CONDITION_TYPE_DATA = 1
  static CONDITION_TYPE_EVENT = 2

  static ACTION_TYPE_REMIND = 0
  static ACTION_TYPE_LOG = 1

  static TIME_CONDITION_ALARM = 0
  static TIME_CONDITION_INTERVAL = 1
  static TIME_CONDITION_SAMPLING = 2
  static TIME_CONDITION_CODENAME_ALARM = "alarm"
  static TIME_CONDITION_CODENAME_INTERVAL = "interval"
  static TIME_CONDITION_CODENAME_SAMPLING = "sampling"
}