export default {
  ATTR_TYPE_NUMBER: 0,
  ATTR_TYPE_TIME: 1,
  ATTR_TYPE_TIMESPAN: 2,
  ATTR_TYPE_TEXT: 3,
  ATTR_TYPE_LOCATION: 5,
  ATTR_TYPE_CHOICE: 6,
  ATTR_TYPE_RATING: 7,
  ATTR_TYPE_IMAGE: 8,
  ATTR_TYPE_AUDIO: 9
}